---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 2
  selector:
   matchLabels:
    app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: brsmnb/brsmnb/kube8s:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1
  labels:
    app: webapp1
spec:
  type: LoadBalancer
  selector:
    app: webapp1
  ports:
  - protocol: TCP
    port: 6655
    targetPort: 8080
