---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp3
spec:
  replicas: 2
  selector:
   matchLabels:
    app: webapp3
  template:
    metadata:
      labels:
        app: webapp3
    spec:
      containers:
      - name: webapp3
        image: brsmnb/kube9s:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp3
spec:
  type: LoadBalancer
  selector:
    app: webapp3
  ports:
  - protocol: TCP
    port: 6655
    targetPort: 8080
