---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp5
  labels:
    app: webapp5
spec:
  replicas: 2
  selector:
   matchLabels:
    app: webapp5
  template:
    metadata:
      labels:
        app: webapp5
    spec:
      containers:
      - name: webapp5
        image: eu.gcr.io/devopsbalu/brsmnb/kube8s:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp5
spec:
  type: LoadBalancer
  selector:
    app: webapp5
  ports:
  - protocol: TCP
    port: 6655
    targetPort: 8080
