---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp6
  labels:
    app: webapp6
spec:
  replicas: 2
  selector:
   matchLabels:
    app: webapp6
  template:
    metadata:
      labels:
        app: webapp6
    spec:
      containers:
      - name: webapp6
        image: eu.gcr.io/devopsbalu/brsmnb/kube8s:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp6
spec:
  type: LoadBalancer
  selector:
    app: webapp6
  ports:
  - protocol: TCP
    port: 6655
    targetPort: 8080
